import type { GeneratedListing } from './types';

const mockItems: GeneratedListing[] = [
  {
    title: 'Nike Air Force 1 Low White — 42 EU — Très bon état',
    description:
      'Nike Air Force 1 Low en cuir blanc, taille 42 EU. Portées quelques fois, très bon état général. Semelle intacte, aucun frottement. Boîte originale fournie.\n\nIconiques et intemporelles, parfaites pour un look streetwear classique. Faciles à assortir à toute tenue.',
    brand: 'Nike',
    category: 'Chaussures › Homme › Baskets',
    color: 'Blanc',
    size: '42 EU',
    material: 'Cuir',
    condition: 'Très bon état',
    price: 75,
    quick_price: 58,
    premium_price: 89,
    keywords: ['nike', 'air force 1', 'af1', 'baskets', 'blanc', 'cuir', '42', 'streetwear', 'sneakers'],
    vinted_filters: [
      { label: 'Pour', value: 'Homme' },
      { label: 'Type', value: 'Baskets' },
      { label: 'Marque', value: 'Nike' },
      { label: 'Taille', value: '42' },
      { label: 'Couleur', value: 'Blanc' },
      { label: 'Matériau', value: 'Cuir' },
      { label: 'État', value: 'Très bon état' },
    ],
  },
  {
    title: 'Carhartt WIP Michigan Coat Marron — Taille L — Bon état',
    description:
      "Carhartt WIP Michigan Coat en Hamilton Brown, taille L. Doublure en flanelle chaude, boutons-pression, poches chauffe-mains. Légères marques d'usure sur les manches, bon état général.\n\nClassique du workwear streetwear, idéale pour l'automne/hiver. Pièce incontournable.",
    brand: 'Carhartt WIP',
    category: 'Vêtements › Homme › Vestes',
    color: 'Marron',
    size: 'L',
    material: 'Coton',
    condition: 'Bon état',
    price: 95,
    quick_price: 75,
    premium_price: 120,
    keywords: ['carhartt', 'wip', 'michigan', 'coat', 'workwear', 'marron', 'L', 'flanelle', 'streetwear'],
    vinted_filters: [
      { label: 'Pour', value: 'Homme' },
      { label: 'Type', value: 'Veste' },
      { label: 'Marque', value: 'Carhartt WIP' },
      { label: 'Taille', value: 'L' },
      { label: 'Couleur', value: 'Marron' },
      { label: 'Matériau', value: 'Coton' },
      { label: 'État', value: 'Bon état' },
    ],
  },
  {
    title: 'Stüssy World Tour Tee Noir — Taille M — Neuf sans étiquette',
    description:
      "T-shirt Stüssy World Tour en coton épais, taille M. Coloris noir, logo brodé sur la poitrine. Jamais porté, état impeccable.\n\nPièce collector de la brand californienne. 100% coton, tombé parfait. Idéale pour les amateurs de streetwear West Coast.",
    brand: 'Stüssy',
    category: 'Vêtements › Homme › T-shirts',
    color: 'Noir',
    size: 'M',
    material: 'Coton',
    condition: 'Neuf sans étiquette',
    price: 55,
    quick_price: 40,
    premium_price: 70,
    keywords: ['stussy', 'world tour', 'tee', 'noir', 'M', 'streetwear', 'california', 'coton', 'logo'],
    vinted_filters: [
      { label: 'Pour', value: 'Homme' },
      { label: 'Type', value: 'T-shirt' },
      { label: 'Marque', value: 'Stüssy' },
      { label: 'Taille', value: 'M' },
      { label: 'Couleur', value: 'Noir' },
      { label: 'Matériau', value: 'Coton' },
      { label: 'État', value: 'Neuf sans étiquette' },
    ],
  },
  {
    title: 'The North Face Nuptse Down Jacket Noir — XL — Très bon état',
    description:
      "Doudoune The North Face Nuptse 700 Fill Down, taille XL, coloris black. Ultra chaude, légère et compressible. Très bon état, quelques légères traces de port sur les poignets.\n\nLa référence ultime en doudoune streetwear. Parfaite pour les saisons froides.",
    brand: 'The North Face',
    category: 'Vêtements › Homme › Doudounes',
    color: 'Noir',
    size: 'XL',
    material: 'Nylon / Duvet',
    condition: 'Très bon état',
    price: 145,
    quick_price: 115,
    premium_price: 179,
    keywords: ['north face', 'nuptse', 'doudoune', 'down', 'noir', 'XL', 'streetwear', '700 fill', 'hiver'],
    vinted_filters: [
      { label: 'Pour', value: 'Homme' },
      { label: 'Type', value: 'Doudoune' },
      { label: 'Marque', value: 'The North Face' },
      { label: 'Taille', value: 'XL' },
      { label: 'Couleur', value: 'Noir' },
      { label: 'Matériau', value: 'Nylon' },
      { label: 'État', value: 'Très bon état' },
    ],
  },
  {
    title: 'Supreme Box Logo Hoodie Gris — Taille L — Bon état',
    description:
      "Supreme Box Logo Hoodie en coton molleton, taille L, coloris gris chiné. Le logo box classique brodé sur la poitrine. Quelques lavages, garde sa forme et sa couleur.\n\nPièce signature Supreme impossible à trouver en boutique. Grail pour tout fan de streetwear.",
    brand: 'Supreme',
    category: 'Vêtements › Homme › Sweats à capuche',
    color: 'Gris',
    size: 'L',
    material: 'Coton',
    condition: 'Bon état',
    price: 220,
    quick_price: 185,
    premium_price: 265,
    keywords: ['supreme', 'box logo', 'hoodie', 'sweat', 'gris', 'L', 'streetwear', 'hype', 'nyc'],
    vinted_filters: [
      { label: 'Pour', value: 'Homme' },
      { label: 'Type', value: 'Sweat à capuche' },
      { label: 'Marque', value: 'Supreme' },
      { label: 'Taille', value: 'L' },
      { label: 'Couleur', value: 'Gris' },
      { label: 'Matériau', value: 'Coton' },
      { label: 'État', value: 'Bon état' },
    ],
  },
  {
    title: 'New Balance 550 White Green — Taille 41 — Neuf avec étiquette',
    description:
      "New Balance 550 coloris blanc/vert, taille 41 EU. Jamais portées, dans la boîte originale avec étiquettes. Semelle en caoutchouc, tige en cuir et mesh.\n\nLe silhouette rétro incontournable de la saison. Confortables et stylées, elles vont avec tout.",
    brand: 'New Balance',
    category: 'Chaussures › Unisexe › Baskets',
    color: 'Blanc/Vert',
    size: '41 EU',
    material: 'Cuir / Mesh',
    condition: 'Neuf avec étiquette',
    price: 85,
    quick_price: 68,
    premium_price: 99,
    keywords: ['new balance', '550', 'blanc', 'vert', '41', 'baskets', 'retro', 'sneakers', 'cuir'],
    vinted_filters: [
      { label: 'Pour', value: 'Unisexe' },
      { label: 'Type', value: 'Baskets' },
      { label: 'Marque', value: 'New Balance' },
      { label: 'Taille', value: '41' },
      { label: 'Couleur', value: 'Blanc' },
      { label: 'Matériau', value: 'Cuir' },
      { label: 'État', value: 'Neuf avec étiquette' },
    ],
  },
];

export async function analyzeClothing(_imageUrls: string[]): Promise<GeneratedListing> {
  await new Promise((r) => setTimeout(r, 2000));
  const randomIndex = Math.floor(Math.random() * mockItems.length);
  return { ...mockItems[randomIndex] };
}
